name: Backpack CI

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set the correct npm version
        run: nvm install && nvm use

      - name: Install dependencies from npm
        run: |
          nvm use
          npm ci

      - name: Build Backpack
        run: |
          nvm use
          npm run build

      - name: Confirm the build hasn't changed any files
        run: ./scripts/check-pristine-state package-lock.json

      - name: Run typecheck
        run: |
          nvm use
          npm run typecheck

      - name: Check if any README.md files have changed
        id: checkReadmeChanges
        run: echo ::set-output name=readmeChanged::$(./scripts/check-readme-changes)
        if: github.ref == 'refs/heads/main'